### ISSUE TITLE
After changing email address user do not get email with subscribe possibility

### ISSUE THREAD

**Issue by Quer1234** [DevAdventCalendar/DevAdventCalendar#245]
**To Reproduce**
1. Create account with email address '1'
2. Change email address into '2'

**Current behavior**
User do not receive email notification with subscribe possibility 

**Expected behavior**
After changing email address user do not receive email with information about subscribe possibility

**Screenshots**

**Additional context**

**Comment by szrtGreg** [comment]
**To Reproduce**
Steps to reproduce the behavior:

    1. Create account with email address '1'
    2. Change email address into '2'

I did some tests and here are outcome:

**Current behavior**
User gets email to newly changed inbox (email address 2) 

![obraz](https://user-images.githubusercontent.com/27915290/87140154-53d1c100-c2a1-11ea-8eb6-5410f78c576c.png)


* There is activation link due to security reasons
* Information about subscribe possibility

I think its correct behaviour. If not please let me know. Thanks :)

**Comment by szrtGreg** [comment]
![email](https://user-images.githubusercontent.com/27915290/87140589-0bff6980-c2a2-11ea-9915-e2a8ad091c89.jpg)

**Comment by WTobor** [comment]
I can see that the content of this mail is generated in `SendEmailConfirmationAsync` method. Maybe we should add new parameter `bool isNewEmail = false` and change the message to contain information:
```
Potwierdzenie zmiany maila
Prosimy o potwierdzenie zmiany maila poprzez kliknięcie na link...
```
other parts of the message should stay the same
