### ISSUE TITLE
Space in the answer should not be always ignored

### ISSUE THREAD

**Issue by Quer1234** [DevAdventCalendar/DevAdventCalendar#252]
**To Reproduce**
1. Create question for which answer contain space - for example answer -> Święty Mikołaj
2. Go to this question and type answer - Święty Mikołaj and press send
3. Page was reloaded - answer was treated by system as wrong, probably due to that -> 'Nie martw się, dla uproszczenia usuniemy spacje z odpowiedzi'

**Current behavior**
System probably remove space after typing answer by user, and treat correct answer as wrong due to space.

**Expected behavior**
Space should not be always removed. Correct answer which contain space should be treated as correct answer.

**Screenshots**

**Additional context**

**Comment by WTobor** [comment]
@patrikulus - could you look at that? It is very important!

**Comment by WTobor** [comment]
a temporary solution is to add answers with manually removed spaces (solution from last year)

**Comment by WTobor** [comment]
@smiechuskce - could you take a look at that after your current task?

**Comment by smiechuskce** [comment]
@WTobor Do we still need spaces being totally removed from answers? If so, maybe that solution will be better - simply remove trailing/heading spaces and, as a small addition, replace multiple spaces near each other to just one space. We should also consider removing tabs or new line characters (if possible to pass to the controller).

**Comment by WTobor** [comment]
@smiechuskce sounds great! Yes, let's start with removing trailing/heading spaces and creating tests :)

**Comment by smiechuskce** [comment]
The problem is, I'm not really sure what and where to test. Currently, the whole logic takes just a single line of code, no many more after changes. Can't test this logic itself, because it's not separated from the controller. I could do that but there is another thought - does it make sense? It will be used only in this case, so there is no point creating another class for just this one method doing that simple logic.

I tried also to modify controllers test, just to see what happens if I'll change the answers from sample data. Those tests however pass even without changing logic to not remove spaces. I've checked out this line of TestControllerTests.cs

`207: this._testServiceMock.Setup(x => x.VerifyTestAnswer(It.IsAny<string>(), It.IsAny<List<string>>())).Returns(true);`

I'm a bit confused, because, assuming the test Index_CorrectAnswer_ReturnsAnswerViewModel tests how the controller method will behave if user pass a correct answer. But because of this line above this test will always pass, even if there will be a completely wrong answer passed. I think it doesn't test all the logic controller does for validating the correct answer.

Please correct me if I'm wrong.

**Comment by WTobor** [comment]
@DevAdventCalendar/dac-mentoring-group :)
