### ISSUE TITLE
[PROD] List of scores visible from previous edition

### ISSUE THREAD

**Issue by Quer1234** [DevAdventCalendar/DevAdventCalendar#466]
1. Login into page https://devadventcalendar.pl/Results/Index
2. See the results list
             - old list of scores is visible
             - first columns have strange header 'System.Security.Claims.ClaimsPrincipal'
             - users in the first column - strange visiblity - for example '0UDdlVsxRqkD'

![image](https://user-images.githubusercontent.com/57844124/100438870-0cf33500-30a3-11eb-840c-404ab46b0ec3.png)

**Comment by WTobor** [comment]
a)  old list of scores is visible -> should be fixed by patrikulus already
b)  first columns have strange header 'System.Security.Claims.ClaimsPrincipal' -> need to be changed to 'Nazwa użytkownika'
c) users in the first column - strange visiblity - for example '0UDdlVsxRqkD' -> it is ok, autogenerated user names
