### ISSUE TITLE
Different coutdown in PROD and DEV

### ISSUE THREAD

**Issue by szrtGreg** [DevAdventCalendar/DevAdventCalendar#481]
**To Reproduce**

1. Go to 'https://dev.devadventcalendar.pl/' Countdown is correct

![obraz](https://user-images.githubusercontent.com/27915290/100617978-7e3d1d00-331b-11eb-8407-58f70886db16.png)

Go to PROD 'https://devadventcalendar.pl/' and time is not correct.
![obraz](https://user-images.githubusercontent.com/27915290/100618002-85fcc180-331b-11eb-93e6-85d0925946a3.png)

In both places we use same js file (DevAdventCalendarCompetition\wwwroot\theme-2019\js\main.js)

![obraz](https://user-images.githubusercontent.com/27915290/100618121-b2b0d900-331b-11eb-912e-74bffa83383d.png)

In my opinion we should check time within docker container (it's common) or linux server.

**Current behavior**
Different coutdown in PROD and DEV

**Expected behavior**
Should be same

**Screenshots**

**Additional context**

**Comment by Mejtika** [comment]
![image](https://user-images.githubusercontent.com/28907927/100620261-8054ab00-331e-11eb-9026-e0c7c5dd4b19.png)
![image](https://user-images.githubusercontent.com/28907927/100620282-877bb900-331e-11eb-9237-3ad428911523.png)
It's because changes from the last PR were not deployed yet on PROD, but it's working now as expected.

**Comment by szrtGreg** [comment]
@Mejtika  Thank you!
